### ISSUE TITLE
The canvas is activated to do what work

### ISSUE THREAD

**Issue by gywgithub** [Emigre/openseadragon-annotations#10]
Thank you very much for the nice plugin, I want to know in the plug-in, the lower left corner of the button to activate brush when invoked the openseadragon which methods, because the mouse to click the default of openseadragon will enlarge the picture, I think the custom button to click on the button to activate the canvas brush effect, how to do?

**Comment by ays0110** [comment]
Seconding this request-- the little button in the bottom left is not really that visible.  Allowing some way to hook into the "Draw state activated" function would allow people to build their own "Start Drawing" buttons.

**Comment by ays0110** [comment]
Made a PR to add these two functions in.

**Comment by Emigre** [comment]
@gywgithub I don't really know what do you mean? Could you elaborate? Is this about allowing the user to change the mode to "draw" programatically?
