### ISSUE TITLE
Uncaught TypeError: Super expression must either be null or a function, not undefined

### ISSUE THREAD

**Issue by zhuyinjing** [Emigre/openseadragon-annotations#11]
when i npm install openseadragon-annotations
and i use `import "openseadragon-annotations/dist/openseadragon-annotations.js";`
its error!! the error is `Uncaught TypeError: Super expression must either be null or a function, not undefined`
how should i do?
i really want to know!!!
And i use VUE.js in my project...
help me!!!! please
thanks so much!!!

**Comment by ays0110** [comment]
Confirming that I had this issue as well when trying to incorporate this through uglifier in the rails asset pipeline.  Had to turn off precompilation to get it to work.

**Comment by Emigre** [comment]
@zhuyinjing, could you please give me more information about this issue? Without a bigger description it's difficult for me to tell what the problem could be. If you have an example repo in github that you can share, that could help.

**Comment by JerryGit1** [comment]
Hello, I met the same problem. How did you solve it?

**Comment by JerryGit1** [comment]
> Confirming that I had this issue as well when trying to incorporate this through uglifier in the rails asset pipeline. Had to turn off compression to get it to work.
How to run the source code? I encountered the same problem as the theme. I couldn't use the compressed version. so try your method.
