### ISSUE TITLE
OpenSeadragon.Annotations is not a constructor: Initialization Error

### ISSUE THREAD

**Issue by imoutsatsos** [Emigre/openseadragon-annotations#16]
Trying to initialize the annotation plugin as described in the current documentation, using 
```const annotations = new OpenSeadragon.Annotations({ viewer });``` 
generates an error 
![image](https://user-images.githubusercontent.com/3408226/29462493-8d8ff78a-83fd-11e7-8285-0e555148a096.png)

![image](https://user-images.githubusercontent.com/3408226/29462428-4f987150-83fd-11e7-8180-93e956fe4d04.png)

However, when I use  ``` viewer.initializeAnnotations();``` as in previous versions of the documentation, the plugin loads and initializes without an error.

**Comment by Emigre** [comment]
Hi @imoutsatsos 

I'm in the middle of implementing a number of changes to the plugin to release a new version. For this reason, the readme in the develop branch refers to what will be the next version. [Here you can see](https://github.com/Emigre/openseadragon-annotations/tree/9cd5639d39db7da8f16f0536f3f3ea064a0d320c) the readme for the latest published version, which is the one that is also available in [the npm package](https://www.npmjs.com/package/openseadragon-annotations).

Please, follow those instructions to use the plugin. I should try to create a separate documentation that can be consulted independently of the readme on github, so it can serve as reference for the latest published version, but I have not had the time to do it. Contributions welcomed! : )
