### ISSUE TITLE
Mouse tracking seems very unreliable

### ISSUE THREAD

**Issue by j-hudecek** [Emigre/openseadragon-annotations#2]
![openseadragon-anno](https://cloud.githubusercontent.com/assets/5654699/16075800/9ea4ad40-32f0-11e6-831f-1a0cfb561e0b.PNG)
When I move my mouse slowly the path created seems to jump to the upper left corner

In Opera 38 and FF 47 on W7 64

**Comment by Emigre** [comment]
Thanks for letting me know @j-hudecek, I'll investigate the issue and try to fix it.

**Comment by j-hudecek** [comment]
have a look at my PR it seems to fix it. However, i've made the changes directly in the single .js file so I hope I've changed things in the right place

**Comment by Emigre** [comment]
hey thanks a lot for the PR man : ) I'll take a look at it as soon as I have some time and merge it
