### ISSUE TITLE
Can't load this plugin with OpenseaDragon using vue.

### ISSUE THREAD

**Issue by izumiwing** [Emigre/openseadragon-annotations#34]
![image](https://user-images.githubusercontent.com/19906645/194714382-e66e213e-ddf6-4bf5-a57c-efa43dfe070d.png)

Tired of trying.After npm installed 2 deps,still the viewer.initializeAnnotations seems no use.
How fix it?

**Comment by iangilman** [comment]
I'm not sure the answer to your question, but you might consider looking into https://github.com/recogito/annotorious-openseadragon, which is better maintained than this plugin.

**Comment by izumiwing** [comment]
> I'm not sure the answer to your question, but you might consider looking into https://github.com/recogito/annotorious-openseadragon, which is better maintained than this plugin.

Finally fixed,thanks :D

**Comment by iangilman** [comment]
@izumiwing Great! What did you do to fix it, if I may ask?
