### ISSUE TITLE
Drawing size is huge when zoomed in

### ISSUE THREAD

**Issue by j-hudecek** [Emigre/openseadragon-annotations#4]
When I zoom in and start drawing, the resulting SVG path has stroke-width 0.5 so it's YUGE

![openseadragon-anno2](https://cloud.githubusercontent.com/assets/5654699/16076852/c6f38d02-32f5-11e6-95d0-958349062d04.PNG)

**Comment by Emigre** [comment]
To be honest when I was working on it I did this on purpose, my impression was that it looked better if the stroke was getting better and smaller with the image. But I see now from you using it how the stroke size at that zoom level makes is actually annoying. I'll take a look at your fix and merge it as soon as I have some time

**Comment by Emigre** [comment]
Isn't this issue the same as #6 ?

**Comment by j-hudecek** [comment]
Well one is that when you draw when zoomed in it appears too big and the other that when you draw zoomed out and then you zoom in it is too big. So the code has to adjust stroke-width based on zoom level and on zoom event the code has to change stroke-width of existing paths.

**Comment by Emigre** [comment]
👌

**Comment by Emigre** [comment]
Fixed in 1.0.0

**Comment by Emigre** [comment]
Reopening, as ['vector-effect': 'non-scaling-stroke'](https://github.com/Emigre/openseadragon-annotations/blob/master/src/utils/shapesFactory.js#L15) won't work in Internet Explorer:
[StackOverflow - SVG, vector-effect=“non-scaling-stroke” and IE](http://stackoverflow.com/questions/29792252/svg-vector-effect-non-scaling-stroke-and-ie)

**Comment by Emigre** [comment]
Fixed in 1.0.1 by setting a different `stroke-width` depending on the zoom level. Which is a pity, because it's less performant than `vector-effect: 'non-scaling-stroke'`. As soon as `non-scaling-stroke` is supported by every major browser it would be great to go back to it, as it's a way better solution than setting the width with JavaScript.

**Comment by Emigre** [comment]
See [Microsoft Edge and Internet Explorer Home - Feature Request - SVG non-scaling-stroke](https://connect.microsoft.com/IE/feedback/details/788819/svg-non-scaling-stroke). Closed as 'Won't Fix'.
