### ISSUE TITLE
Zoomed in drawing is huge

### ISSUE THREAD

**Issue by j-hudecek** [Emigre/openseadragon-annotations#6]
When I zoom in on an image the old drawings don't get resized, so they're too wide

**Comment by Emigre** [comment]
hey thanks a lot for your contributions! Do you have an screenshot or a longer description to reproduce this one?

**Comment by j-hudecek** [comment]
![anno-zoom16](https://cloud.githubusercontent.com/assets/5654699/16077116/28fd331c-32f7-11e6-885f-299fae05ed6b.PNG)
![anno-zoom1](https://cloud.githubusercontent.com/assets/5654699/16077117/28ff4c4c-32f7-11e6-9397-7ce9f0aa5afd.PNG)
Same drawing from afar and zoomed in

**Comment by j-hudecek** [comment]
![anno2-zoom8](https://cloud.githubusercontent.com/assets/5654699/16077162/6ec9962e-32f7-11e6-945c-4572216363e1.PNG)
![anno2-zoom1](https://cloud.githubusercontent.com/assets/5654699/16077161/6ec64eb0-32f7-11e6-80fa-29d2f60c68cf.PNG)
This is how it looks after the fix

**Comment by Emigre** [comment]
Fixed in 1.0.0
